# Generated by Django 5.0.6 on 2024-06-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="my@mail.com", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="1111", max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default="surename", max_length=120),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="name", max_length=120),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel_fellows.user",
                    ),
                ),
            ],
        ),
    ]
