# Generated by Django 5.0.6 on 2024-06-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "travel_fellows",
            "0002_user_email_user_password_user_surname_alter_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
