# Generated by Django 5.0.6 on 2024-07-23 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "travel_fellows",
            "0003_remove_userprofile_hashtags_alter_userprofile_photo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="hashtag",
            old_name="name",
            new_name="hashtag",
        ),
    ]
