# Generated by Django 5.0.6 on 2024-07-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0004_rename_name_hashtag_hashtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="transport",
        ),
        migrations.CreateModel(
            name="UserTransportation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plane", models.BooleanField(default=True)),
                ("bus", models.BooleanField(default=True)),
                ("bike", models.BooleanField(default=False)),
                ("feet", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transportation",
                        to="travel_fellows.userprofile",
                    ),
                ),
            ],
        ),
    ]
