# Generated by Django 5.0.6 on 2024-07-25 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0005_remove_userprofile_transport_usertransportation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransportation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
