# Generated by Django 5.0.6 on 2024-06-19 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0006_userprofile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="photo",
        ),
    ]
