# Generated by Django 5.0.6 on 2024-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0007_remove_userprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.FilePathField(default="photos/default.jpg"),
        ),
    ]
