# Generated by Django 5.0.6 on 2024-07-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0007_alter_usertransportation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransportation",
            name="bus",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usertransportation",
            name="feet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usertransportation",
            name="plane",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usertransportation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
