# Generated by Django 5.0.6 on 2024-06-19 19:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0008_userprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="destinations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="food",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hashtags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hobbies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="music",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="transport",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
    ]
