# Generated by Django 5.0.6 on 2024-07-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0008_alter_usertransportation_bus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplans",
            name="length",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="userplans",
            name="kids",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userplans",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
