# Generated by Django 5.0.6 on 2024-06-23 20:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0009_userprofile_destinations_userprofile_food_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "plans",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        default=list,
                        size=None,
                    ),
                ),
                ("companions", models.IntegerField(default=1)),
                ("dates_start", models.DateField()),
                ("dates_end", models.DateField()),
                ("kids", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="travel_fellows.user",
                    ),
                ),
            ],
        ),
    ]
