# Generated by Django 5.0.6 on 2024-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0009_userplans_length_alter_userplans_kids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplans",
            name="kids",
            field=models.BooleanField(default=False),
        ),
    ]
