# Generated by Django 5.0.6 on 2024-08-10 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0010_alter_userplans_kids"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userplans",
            options={"verbose_name": "User Plans", "verbose_name_plural": "User Plans"},
        ),
        migrations.AlterField(
            model_name="userplans",
            name="destinations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userplans",
            name="kids",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="userplans",
            name="plans",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
