# Generated by Django 5.0.6 on 2024-08-19 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "travel_fellows",
            "0011_alter_userplans_options_alter_userplans_destinations_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplans",
            name="companions",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(50),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userplans",
            name="length",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(120),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
