# Generated by Django 5.0.6 on 2024-07-04 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0011_authuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authuser",
            old_name="email",
            new_name="username",
        ),
    ]
