# Generated by Django 5.0.6 on 2024-07-04 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0012_rename_email_authuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authuser",
            old_name="username",
            new_name="email",
        ),
    ]
