# Generated by Django 5.0.6 on 2024-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0013_alter_userplans_companions_alter_userplans_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplans",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
