# Generated by Django 5.0.6 on 2024-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0016_delete_authuser_user_groups_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
