# Generated by Django 5.0.6 on 2024-07-05 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0018_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="username",
        ),
    ]
