# Generated by Django 5.0.6 on 2024-07-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0019_rename_email_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AV", "Avia"),
                    ("AU", "Automobile"),
                    ("BI", "Bicycle"),
                    ("HI", "Hiking"),
                ],
                default="AU",
                max_length=2,
            ),
        ),
    ]
