# Generated by Django 5.0.6 on 2024-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0020_alter_userprofile_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.FileField(default=False, upload_to="img"),
        ),
    ]
