# Generated by Django 5.0.6 on 2024-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0021_alter_userprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(default=False, upload_to="img"),
        ),
    ]
