# Generated by Django 5.0.6 on 2024-07-11 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0022_alter_userprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                upload_to="img",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            ".JPEG",
                            ".JPG",
                            ".PNG",
                            ".GIF",
                            ".jpg",
                            ".jpeg",
                            ".png",
                            ".gif",
                        ]
                    )
                ],
            ),
        ),
    ]
