# Generated by Django 5.0.6 on 2024-07-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_fellows", "0025_alter_userprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="travel_fellows/profile"),
        ),
    ]
